# Generated by Django 4.0.5 on 2025-12-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_company',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
